'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1026
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ArmStatusPanel.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1T() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1T", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _1T2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1T2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2T() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2T", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _2T2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_2T2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3T() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3T", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _3T2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_3T2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _4T() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_4T", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _4T2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_4T2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5T() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5T", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _5T2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_5T2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _6T() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_6T", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _6T2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_6T2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _7T() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_7T", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _7T2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_7T2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _8T() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_8T", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _8T2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_8T2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _9T() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_9T", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _9T2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_9T2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property armed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("armed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property B1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("B1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fighting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fighting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to background,icons
        '''default,default
        '''rock,dark
        '''skull,
        '''skull2,
        '''crystal,
        '''logo,
        '''.
        '''</summary>
        Friend ReadOnly Property GraphicSets() As String
            Get
                Return ResourceManager.GetString("GraphicSets", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property health() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("health", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property heavy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heavy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property light() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("light", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logooverlay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logooverlay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property manageable() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("manageable", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mounted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mounted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NewArmLogo() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("NewArmLogo", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property resting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("resting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property running() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("running", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sitting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sitting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sneaking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sneaking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stamina() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stamina", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property standing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("standing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stun", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property unarmed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unarmed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property walking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("walking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
